### ISSUE TITLE
[SR-15880] Add ability to swift-format to only re-format certain ranges of a file

### ISSUE THREAD

**Issue by ahoppen** [apple/swift-format#297]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15880      |
   |Radar             | rdar://112190730         |
   |Original Reporter | @ahoppen      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift-format    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 55c33a2de9a258402756fbffd509321e

  </details>

**Issue Description:**

swift-format currently only has the ability to re-format the entire file. Especially when working in projects whose current indentation cannot be fully described by swift-format configuration files and where re-formatting the entire source code is not an option, it makes swift-format basically unusable.

What I do enjoy is git-clang-format’s ability to only re-format the lines that I touched. It would be nice if swift-format had a similar functionality to only format certain ranges of a file.

**Comment by vemishel** [comment]
Just mentioning that this functionality could be very nice to have 🙂

**Comment by MahdiBM** [comment]
Noticing Saafo's issue, i just want to bump this up and mention that i think this is a very important feature to make an IDE like vscode useable for _writing_ Swift code. 
My attempts to add such a feature to vknabel's formatter extensions did not turn out perfect and it seems to me that it requires built-in support in the formatter tool itself. For now I'm using a local version of vknabel's SwiftFormat (not swift-format) which uses diffing mechanisms to only format a specific range of lines, and although it's not perfect at times, it's still far better than not having it at all, specially combined with [on-type formatting](https://github.com/vknabel/vscode-swiftformat/pull/32).
