### ISSUE TITLE
[SR-14139] Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-format#312]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14139      |
   |Radar             | rdar://problem/73832515         |
   |Original Reporter | maticzav (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

I am running this on 11.1 MacOS Big Sur with 12.0 XCode.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift-format, SwiftSyntax    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2fe2fd02d5afe157f55c9241f621b7e2

  </details>

**Issue Description:**

Hi!

 

I hope this is not a silly question; how do you use this library inside another Swift library? I am maintaining a GraphQL client library that heavily relies on code generation. Since the code is mainly unformatted, I'd like to format it before writing it out on a disk.

 

I am trying to use \`swift-format\` (which relies on \`swift-syntax\`) and I am getting a strange error when using the library.

 

\`\`\`

Undefined symbols for architecture x86_64:  
"\_$s11SwiftFormat0A9FormatterC13configuration16diagnosticEngineAC0aB13Configuration0G0V_0A6Syntax010DiagnosticF0CSgtcfC", referenced from:  
\_$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o  
"\_$s11SwiftFormat0A9FormatterC6format6source15assumingFileURL2toySS_10Foundation0H0VSgxztKs16TextOutputStreamRzlF", referenced from:  
\_$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o  
"\_$s11SwiftFormat0A9FormatterCMa", referenced from:  
\_$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o  
"\_$s24SwiftFormatConfiguration0C0VACycfC", referenced from:  
\_$sSS19SwiftGraphQLCodegenE6formatSSyKF in String+Format.swift.o  
ld: symbol(s) not found for architecture x86_64

\`\`\`

I've seen the [note](#embedding-swiftsyntax-in-an-application) in swift-syntax's README that talks about linking the library, and I've found a similar issue (and its \[fix\|[https://github.com/SwiftDocOrg/homebrew-formulae/commit/af4cd47](https://github.com/SwiftDocOrg/homebrew-formulae/commit/af4cd47)),)\]), but the other libraries in the examples section in that README don't rely on any such script.

 

Can you help me? What am I doing wrong? What should I look at to understand the error message?

 

Thank you!

 

\> I know this is not ideal, but you can find all the code in \[SwiftGraphQL\|<https://github.com/maticzav/swift-graphql/tree/next>\]'s repo.

**Comment by allevato** [comment]
Is this issue still relevant? If so, please re-open it.
