### ISSUE TITLE
[SR-12785] swift-format -m lint has zero exit code after identifying style violations

### ISSUE THREAD

**Issue by tcldr** [apple/swift-format#327]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12785      |
   |Radar             | None         |
   |Original Reporter | @tcldr      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963791-5fe0edd5-dd40-4520-a8e3-921b2e9dd628.gz)

      
<details>
  <summary>Environment</summary>

swift-format swift-5.2-branch  
Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)  
Target: x86_64-apple-darwin19.4.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift-format    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 309a6cbb23c057de7ad21f94da974b48

  </details>

**Issue Description:**

It seems that swift-format should set a non-zero Xcode when it identifies a style violation.

However, violations are returned with a zero error which may complicate integration with other parts of a build pipeline:

    $ swift-format -m lint Test.swift
    /Users/tcldr/Desktop/Test.swift:1:1: warning: [Indentation] remove all leading whitespace
    /Users/tcldr/Desktop/Test.swift:1:8: warning: [Spacing]: remove 1 space
    /Users/tcldr/Desktop/Test.swift:1:18: warning: [Spacing]: remove 3 spaces
    $ echo $?
    0

**Comment by allevato** [comment]
This was fixed by the addition of the `--strict` flag.
