### ISSUE TITLE
[SR-12714] Explicit self.

### ISSUE THREAD

**Issue by weissi** [apple/swift-format#329]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12714      |
   |Radar             | None         |
   |Original Reporter | @weissi      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift-format    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0eee30a579bfbe4ae0442eb637819834

  </details>

**Issue Description:**

AFAIK, `swift-format` doesn't support adding explicit `self.` everywhere. It would be great if it could do that.

**Comment by pronebird** [comment]
It does not support trimming implicit `self` either, so would be good to have both options.

**Comment by allevato** [comment]
Adding or removing explicit `self` would likely require semantic information about the symbols, not just the syntax, to distinguish identifiers and know whether they're members of `self` and that the code could be changed without changing its behavior.

It might be possible to approximate it by tracking symbols in their lexical scopes and use that to determine which symbol is being referred to, we wouldn't have access to the compiler `Decl`s that would let us be 100% confident that `self` is the same as the container for some property `x` if it's also in the presence of other shadowing names.
