### ISSUE TITLE
[SR-12521] swift-format 5.2 branch fails with error "Too many unresolved delmiter token lengths"

### ISSUE THREAD

**Issue by swift-ci** [apple/swift-format#331]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12521      |
   |Radar             | rdar://problem/62201696         |
   |Original Reporter | killectro (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 11.4

Swift 5.2

Branch: \`swift-5.2-branch\`

Commit SHA: \`1fda39893d3652a9a3f1673565a227f843d59f3c\`

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift-format    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1363f6c20f83c269551863c5a4f54343

  </details>

**Issue Description:**

I was curious about the current state of the project so I decided to clone it and run it on my work codebase.

Running the swift-format 5.2 branch fails with error "Too many unresolved delmiter token lengths" when run on my current project. I was able to narrow it down to the following minimal example:

Broken:

``` java
class Foo {
    init(bar: Int) {}
}
```

 

Working:

 

``` java
class Foo {
    init() {}
}
```

I dug through the swift-format source a little bit but wasn't able to figure out the root of the problem since I am pretty unfamiliar with the structure of how it works.

 

Bonus bug, delimiter is spelled incorrectly in the error message!

 

.swift-format:

    {
      "maximumBlankLines" : 1,
      "lineLength" : 100,
      "lineBreakAroundMultilineExpressionChainComponents" : true,
      "tabWidth" : 4,
      "prioritizeKeepingFunctionOutputTogether" : true,
      "indentConditionalCompilationBlocks" : true,
      "indentation" : {
        "spaces" : 4
      },
      "respectsExistingLineBreaks" : true,
      "lineBreakBeforeEachArgument" : true
    }

**Comment by allevato** [comment]
The example above passes with the latest formatter, so this appears to have been fixed.
