### ISSUE TITLE
False positive for `RemoveLine` when using `#if` directive

### ISSUE THREAD

**Issue by FlineDevPublic** [apple/swift-format#372]
I've just ran across a weird auto-correction and lint warning when I tried to provide iOS-only modifiers in a SwiftUI view. When running the `lint` command in Xcode, the warnings look like this:

![Screen Shot 2022-05-20 at 13 01 02](https://user-images.githubusercontent.com/97410916/169514619-62a0485b-066d-4d4a-beaf-a17573deb7cb.png)

And when running the corrections, swift-format corrects my code to this (which is ugly IMO):
![Screen Shot 2022-05-20 at 13 05 24](https://user-images.githubusercontent.com/97410916/169515217-f911ec9b-9397-4a5b-9aeb-42d077013da5.png)

I also couldn't find a configuration option to turn these warnings off, too. Both `RemoveLine` and `Indentation` are false positives in my opinion and I couldn't find either of these rules in the config file.

Also, disabling the `Indentation` didn't work, this still shows a violation:
```swift
.navigationBarTitle(L10n.Timer.EditSummaryScreen.title)  // swift-format-ignore: Indentation
```

---

By the way, I'm not sure if just reporting issues with a normal title is the correct approach here. The GitHub  organization doesn't seem to have an [issue template](https://github.blog/2016-02-17-issue-and-pull-request-templates/) yet (with things like "steps to reproduce", "expected state" etc.). It feels weird being the first reporting an issue without the `[SR...]` prefix after the migration from JIRA. 😅 

---
_This issue was reported during my regular **Open Source live stream on [Twitch](https://www.twitch.tv/jeehut)**. Follow me there to support my work!_

**Comment by allevato** [comment]
This should be fixed by https://github.com/apple/swift-format/pull/383 once it's merged.
