### ISSUE TITLE
`get throws` is removed when format is performed

### ISSUE THREAD

**Issue by ruiaureliano** [apple/swift-format#373]
If we want a computed var that throws an error the only way (as far as I know) is to make it like this 

```swift
var decompressed: Data {
   get throws {
      try (self as NSData).decompressed(using: .lz4) as Data
   }
}

```
But once we perform the format it turns into this:

```swift
var decompressed: Data {
   try (self as NSData).decompressed(using: .lz4) as Data
}
```

Which is not the same

**Comment by allevato** [comment]
Do you have a more complete example of this? Which version of swift-format are you using? This should be fixed by https://github.com/apple/swift-format/pull/279, which was in the 0.50600.0 release.

**Comment by allevato** [comment]
Closing this as this specific example appears to be working in `main`.
