### ISSUE TITLE
Unable to get swift-format to work as a package with the VSCode extension on Ubuntu 22.04

### ISSUE THREAD

**Issue by Zingam** [apple/swift-format#376]
I use Ubuntu 22.04 with Swift 5.6 from swift.org.
I filed a complaint against the VSCode extension:

https://github.com/vknabel/vscode-apple-swift-format/issues/12

```Swift
// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "SwiftTest",
    products: [
        .executable(name: "SwiftTest", targets: ["SwiftTest"]),
    ],
    dependencies: [
        // My dependencies
        // Dev deps
       .package(url: "https://github.com/apple/swift-format.git", branch: "release/5.7"),
       .package(url: "https://github.com/realm/SwiftLint.git", from: "0.47.1"),
    ],  
    targets: [
        .executableTarget(name: "SwiftTest"),
        .testTarget(name: "SwiftTestTests",
        dependencies: [
            .byName(name: "SwiftTest"),
        ]
        )
    ]
)
```

It looks like the compilation fails:

> $ swift run -c release swift-format --version
Fetching https://github.com/apple/swift-format.git from cache
Fetched https://github.com/apple/swift-format.git (0.77s)
Fetching https://github.com/apple/swift-argument-parser.git from cache
Fetched https://github.com/apple/swift-argument-parser.git (0.73s)
Fetching https://github.com/apple/swift-syntax from cache
Fetched https://github.com/apple/swift-syntax (1.13s)
Fetching https://github.com/apple/swift-tools-support-core.git from cache
Fetched https://github.com/apple/swift-tools-support-core.git (0.90s)
Fetching https://github.com/realm/SwiftLint.git from cache
Fetching https://github.com/jpsim/Yams.git from cache
Fetching https://github.com/scottrhoyt/SwiftyTextTable.git from cache
Fetched https://github.com/scottrhoyt/SwiftyTextTable.git (0.62s)
Fetching https://github.com/drmohundro/SWXMLHash.git from cache
Fetched https://github.com/jpsim/Yams.git (1.23s)
Fetching https://github.com/jpsim/SourceKitten.git from cache
Fetched https://github.com/drmohundro/SWXMLHash.git (0.64s)
Fetching https://github.com/apple/swift-system.git from cache
Fetched https://github.com/realm/SwiftLint.git (1.73s)
Fetching https://github.com/krzyzanowskim/CryptoSwift.git from cache
Fetched https://github.com/apple/swift-system.git (1.04s)
Computing version for https://github.com/realm/SwiftLint.git
Fetched https://github.com/krzyzanowskim/CryptoSwift.git (1.09s)
Fetched https://github.com/jpsim/SourceKitten.git (1.89s)
Computed https://github.com/realm/SwiftLint.git at 0.47.1 (1.42s)
Computing version for https://github.com/apple/swift-system.git
Computed https://github.com/apple/swift-system.git at 1.1.1 (0.68s)
Computed https://github.com/realm/SwiftLint.git at 0.47.1 (0.00s)
Computing version for https://github.com/krzyzanowskim/CryptoSwift.git
Computed https://github.com/krzyzanowskim/CryptoSwift.git at 1.4.3 (0.71s)
Computing version for https://github.com/scottrhoyt/SwiftyTextTable.git
Computed https://github.com/scottrhoyt/SwiftyTextTable.git at 0.9.0 (0.65s)
Computing version for https://github.com/jpsim/Yams.git
Computed https://github.com/jpsim/Yams.git at 4.0.6 (0.68s)
Computing version for https://github.com/jpsim/SourceKitten.git
Computed https://github.com/jpsim/SourceKitten.git at 0.32.0 (0.70s)
Computing version for https://github.com/drmohundro/SWXMLHash.git
Computed https://github.com/drmohundro/SWXMLHash.git at 6.0.0 (0.68s)
Creating working copy for https://github.com/jpsim/Yams.git
Working copy of https://github.com/jpsim/Yams.git resolved at 4.0.6
Creating working copy for https://github.com/apple/swift-format.git
Working copy of https://github.com/apple/swift-format.git resolved at release/5.7
Creating working copy for https://github.com/apple/swift-argument-parser.git
Working copy of https://github.com/apple/swift-argument-parser.git resolved at main
Creating working copy for https://github.com/scottrhoyt/SwiftyTextTable.git
Working copy of https://github.com/scottrhoyt/SwiftyTextTable.git resolved at 0.9.0
Creating working copy for https://github.com/drmohundro/SWXMLHash.git
Working copy of https://github.com/drmohundro/SWXMLHash.git resolved at 6.0.0
Creating working copy for https://github.com/jpsim/SourceKitten.git
Working copy of https://github.com/jpsim/SourceKitten.git resolved at 0.32.0
Creating working copy for https://github.com/krzyzanowskim/CryptoSwift.git
Working copy of https://github.com/krzyzanowskim/CryptoSwift.git resolved at 1.4.3
Creating working copy for https://github.com/realm/SwiftLint.git
Working copy of https://github.com/realm/SwiftLint.git resolved at 0.47.1
Creating working copy for https://github.com/apple/swift-syntax
Working copy of https://github.com/apple/swift-syntax resolved at main
Creating working copy for https://github.com/apple/swift-tools-support-core.git
Working copy of https://github.com/apple/swift-tools-support-core.git resolved at main
Creating working copy for https://github.com/apple/swift-system.git
Working copy of https://github.com/apple/swift-system.git resolved at 1.1.1
Building for production...
remark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with whoremark: Incremental compilation has been disabled: it is not compatible with who/home/xxx/Desktop/SwiftFormatTest/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:150:9: error: cannot find 'swiftparse_parser_set_language_version' in scope
swiftparse_parser_set_language_version(c_parser, languageVersionCString)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xxx/Desktop/SwiftFormatTest/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:154:7: error: cannot find 'swiftparse_parser_set_enable_bare_slash_regex_literal' in scope
swiftparse_parser_set_enable_bare_slash_regex_literal(c_parser, enableBareSlashRegexLiteral)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[19/21] Compiling SwiftSyntaxParser CNodes.swift

**Comment by allevato** [comment]
If you're using Swift 5.6, you need to use one of the `0.50600.x` releases of swift-format; the compiler and swift-format need to be the same major/minor version to be compatible. Can you try changing `release/5.7` to `0.50600.1` and see if that resolves your issue?

**Comment by Zingam** [comment]
Thanx!
