### ISSUE TITLE
Async support for initializers

### ISSUE THREAD

**Issue by Maschina** [apple/swift-format#379]
What I have recognized is that swift-format cannot handle `init(...) async`. It will dump a "error: file contains invalid or unrecognized Swift syntax.".

**Comment by allevato** [comment]
This was a bug in swift-syntax's handling of `async` initializers, which was fixed in https://github.com/apple/swift-syntax/pull/499. This now works in `main`:

```shell
$ .build/debug/swift-format <<'EOF'
class Foo {
    init(bar: Int) async {} }
EOF
```

Output:
```
class Foo {
  init(bar: Int) async {}
}
```
