### ISSUE TITLE
build on windows, error: plugin process ended by an uncaught signal: 1033

### ISSUE THREAD

**Issue by garymaxallen** [apple/swift-format#422]
`swift.exe build -c release`
```
error: plugin process ended by an uncaught signal: 1033 <command: d:\tmp\swift-format\.build\plugins\cache\generate_pipeline_plugin.exe>, <output:
>
```
![image](https://user-images.githubusercontent.com/10022333/195314260-06765f89-369c-494e-a757-d12a2fcdfd02.png)

**Comment by compnerd** [comment]
As a quick sanity check/workaround, could you please try the following:

```
path C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\pm\PluginAPI;%Path%
swift build -c release
```

I suspect that the error 1033 is "dll not found" as we do not inject the path to the plugin API runtime support into Path (there is no rpath equivalent on Windows, `Path` is the approach) when the plugin is executed, and you happened to actually properly receive an error message for that.

**Comment by allevato** [comment]
We had to revert the plugin for other reasons, so can you please pull down the latest changes and try the build again?

**Comment by garymaxallen** [comment]
> As a quick sanity check/workaround, could you please try the following:
> 
> ```
> path C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift\pm\PluginAPI;%Path%
> swift build -c release
> ```
> 
> I suspect that the error 1033 is "dll not found" as we do not inject the path to the plugin API runtime support into Path (there is no rpath equivalent on Windows, `Path` is the approach) when the plugin is executed, and you happened to actually properly receive an error message for that.



> We had to revert the plugin for other reasons, so can you please pull down the latest changes and try the build again?




I pull down the latest code,  not working
```
[5/10] Compiling SystemPackage Errno.swifterror: command Archiving d:\tmp\swift-format\.build\x86_64-unknown-windows-msvc\release\libSwiftSyntax.a failed: unable to spawn process 'ar' (The system cannot find the file specified.
)
```
![image](https://user-images.githubusercontent.com/10022333/195533916-bd5224e3-9022-487c-ab8b-cf05850ccd37.png)

**Comment by compnerd** [comment]
Please use a more recent Swift toolchain.  Something like the 2022-10-08-a snapshot should do.  Alternatively, workaround this by using `set AR=llvm-ar`.
