### ISSUE TITLE
Cannot invoke plugins from command line

### ISSUE THREAD

**Issue by lucteo** [apple/swift-format#483]
Hi

I'm trying to add swift-format to our project; we aim at being able to run this manually, and from our CI pipeline.
swift-format is added as a dependency in our Package.swift. (in my tests, I'm using `0.50800.0-SNAPSHOT-2022-12-29-a` tag).

If I run "Lint Source Code" or "Format Source Code" from XCode, everything works ok.
However, If I try to run it from command line, I get the following errors:

```
$ swift package plugin lint-source-code
Building for debugging...
Build complete! (0.58s)
Error: '--recursive' is only valid when formatting or linting files
Usage: swift-format lint [--configuration <configuration>] [--assume-filename <assume-filename>] [--recursive] [--ignore-unparsable-files] [--parallel] [--color-diagnostics] [--no-color-diagnostics] [<paths> ...] [--strict]
  See 'swift-format lint --help' for more information.
error: swift-format invocation failed: NSTaskTerminationReason(rawValue: 1):64
```

Can you please help me make this work?

Thank you very much

**Comment by dabrahams** [comment]
Lucian do you have a pointer to the package plugin you're working with?

**Comment by lucteo** [comment]
The ones included in swift-format: https://github.com/apple/swift-format/tree/main/Plugins (in the above example, I'm using the linter plugin)

**Comment by dabrahams** [comment]
I see, there are no tests for those in the project.  Nice.  You can use "swift package edit swift-format" and then go in and add printing to [the place where the command is issued](https://github.com/apple/swift-format/blob/main/Plugins/LintPlugin/plugin.swift#L19), to see what it's actually trying to do.

**Comment by dabrahams** [comment]
My guess is that this thing should not be trying to use `--recursive` at all.  Its logic is very weird, such that it lints everything in the same directory as a target file, whether it's a target or not.  Also submits a directory for each target file, without uniquing them, which could be problematic depending on how SPM deals with it.

**Comment by macshome** [comment]
I'm going to open a PR for the `strict` thing, but I also debugged the issues that @lucteo was running into.

The command plugins operate on a target, currently, not a directory. So you need to tell it what target to lint.
`swift package plugin lint-source-code --target swift-format`

This mirrors the behavior of the Xcode plugin, if you want to run `swift-format` as a tool on a directory I would just call it directly.

**Comment by dabrahams** [comment]
Maybe I'm misunderstanding the logic I described [here](https://github.com/apple/swift-format/issues/483#issuecomment-1432233631), but by my reading it looks like it would _seem_ to work in “normal” projects, but break in unusual projects, e.g. when there are non-target swift files in the same directory as Swift files.  I also think you should reconsider whether it's really right to submit whole directories to swift-format.

**Comment by macshome** [comment]
In the context of using a plugin though the target that is passed is the directory that the target code lives in. It doesn't seem to have any other way of passing a location. It also though only seems to read `.swift` files and there is an option to ignore non-parseable files.

When running as a standalone tool, `swift-format` seems to have more flexibility on the input.

**Comment by dabrahams** [comment]
That's very strange. The plug-in I built gets passed individual files: https://github.com/dabrahams/citron/blob/ecfdaf5db81dcea8c7162f85e6defc5a7052b618/Plugins/CitronParserGenerator/CitronParserGenerator.swift

**Comment by macshome** [comment]
Ahh, that helps immensely and I can get the source files now from the target.

When using `--recursive` though it's already building a file list of the `.swift` files in the project directory with the [FileItereator](https://github.com/apple/swift-format/blob/main/Sources/swift-format/Utilities/FileIterator.swift) utility.

Honestly I don't have a lot of use for the lint command plugin as the warnings don't show up in Xcode as they aren't build warnings. For that we need a BuildPlugin.

I'll make a new issue for the removal of `--strict` in the lint plugin default args and open a PR for it. The code isn't very testable for that sort of thing, but I'll try to figure something out.

For the scope of this particular ticket it seems that calling a Command Plugin without a target specified was the actual issue. I think that can probably be fixed with documentation on how to call a command plugin from the CLI.

**Comment by macshome** [comment]
Opened PR #489 for the `--strict` thing.
