### ISSUE TITLE
Wrapping attributes in #if fails to format

### ISSUE THREAD

**Issue by mbrandonw** [apple/swift-format#487]
The following is valid Swift code:

```swift
#if swift(>=5.8)
  @_documentation(visibility: public)
#endif
public func _print() {}
```

But running swift-format on it produces some errors, like this:

```
error: expected expression in list of expressions
error: expected declaration
```

**Comment by stackotter** [comment]
I can't reproduce this on `main`, has the transition to the Swift-based parser fixed this perhaps?

**Comment by allevato** [comment]
The error message is indicative of the parser not supporting this syntax at the time the issue was filed. It appears to have been fixed.
