### ISSUE TITLE
command not found swift-format

### ISSUE THREAD

**Issue by Kuro7070** [apple/swift-format#502]
After installing swift-format through my console, it cant find the command swift-format. Same for xcode.
If I install it with brew, it works but you can't change the version and I want it to install about the official way.
What could be my problem?

That's my code in the xcode buildphase
`if which swift-format >/dev/null; then
    swift-format lint -r -p --configuration formatConfig.json "${PROJECT_DIR}/ChatApp"
else
    echo "warning: swift-format not installed"
fi`

**Comment by stackotter** [comment]
What commands did you use to install `swift-format`? My guess is that the built executable didn't get added/copied to your path. I believe you can fix that by running `cp .build/release/swift-format /usr/local/bin/` inside the swift format directory. Another method would be to use [Mint](https://github.com/yonaskolb/Mint) to install the tool, however Mint is not really being maintained anymore and I don't think it's the best to recommend it.

**Comment by stackotter** [comment]
Hm had a feeling that might happen with my naive copy-to-path solution. You can installing it with Mint or replacing your command with the following (temporarily):

```
/path/to/repo/.build/release/swift-format lint -r -p --configuration formatConfig.json "${PROJECT_DIR}/ChatApp"
```

I'm interested why adding it to your path didn't work though, try running the following commands. Make sure to replace `/path/to/repo` with the correct absolute path to the swift format repo.

```
rm /usr/local/bin/swift-format
echo "\nexport PATH=\"$PATH:/path/to/repo/.build/release\"" >> ~/.zshenv
```

The first removes the `swift-format` binary we moved to your path of course, and the second adds the folder containing the built binary (and accompanying libraries) to your path.

You may need to restart Xcode for that to work.

**Comment by Kuro7070** [comment]
Sure, thx for the help @stackotter 
If I add the complete path before the command, it works in xcode
`/Users/zilke/Documents/swift-format/.build/release/swift-format lint -r -p --configuration formatConfig.json "${PROJECT_DIR}/ChatApp"`

But the command swift-format stillt doesn't work
That is the command I tried. Just in case I did something wrong
`echo "\nexport PATH=\"$PATH:/Users/zilke/Documents/swift-format/.build/release\"" >> ~/.zshenv`

**Comment by stackotter** [comment]
If you run `swift-format` in terminal does that work? The issue could be that Xcode is ignoring the new addition to the path (not sure if it respects `.zshenv`, haven't used it in a while).

Mint is the only tool that I know of for installing Swift command line tools from source. There was talk about adding a `swift install` command to swiftpm, but that died away sadly.

**Comment by stackotter** [comment]
Yeah that's strange, something weird is going on with your path. My only ideas for why that might be are: you're not using zsh (common on older macos versions), your terminal isn't causing `~/.zshenv` to be loaded (dunno why that'd be), or the path addition command I gave you failed (you should check the contents of `~/.zshenv`).

Hopefully your teamleader can help solve the issue, they should have more luck given they have access to the device 👍

**Comment by Wendell0817** [comment]
I'm having the same issue with XC 14.2.  Other devs on my team using 14.1 have no issues with `swift-format`.  Any updates on this @stackotter  ?

**Comment by allevato** [comment]
I'm not sure what's causing the issues in the previous versions, but you may want to try out the just-released 508.0.0 version. It no longer depends on `lib_InternalSwiftSyntaxParser.dylib` nor does it have the requirement that it matches the specific version of the toolchain you're using (beyond being able to compile it in the first place).

(I don't control the Brew distribution, so you'd have to install it by downloading the release sources here and building them with `swift build`.)

**Comment by xavierliancw** [comment]
@Kuro7070, you should double check your `~/.zshenv` file, checking to see if your command actually made it in. You may also have to do `source ~/.zshenv` or restart your computer.

The crux of your problem is that your freshly-compiled executable isn't visible to your $PATH. Adding it to your `.zshenv` should've done the trick though. (Although, I'm not actually sure what `.zshenv` does...)

I would've put into my `~/.zprofile` if I wanted to modify my path (but that's not  what I did).
I instead moved all relevant build artifacts to a folder I made, `/Applications/Utilities/CLI/swift-format`.
Then I symlinked the main executable to `/usr/local/bin/swift-format`.
That way I avoided messing with my $PATH, and it's a little closer to Linux conventions.

**Comment by Wendell0817** [comment]
@allevato thanks! 508.0.0 version is working for me!

**Comment by Kuro7070** [comment]
Hi guys, I tried again yesterday and now it works. I don't know why the command to change the bin folder didn't work for me the first time.
Solution:
enter this in your terminal
`cp .build/release/swift-format /usr/local/bin/`
`cp .build/release/lib_InternalSwiftSyntaxParser.dylib /usr/local/bin/`
