### ISSUE TITLE
Fatal error: editor placeholder in source file

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-format#526]
Run swift-format on this source:
```
switch <#value#> {
case <#pattern#>:
	<#code#>
default:
	<#code#>
}
```
I get the following errors:
1:8: editor placeholder in source file
2:6: editor placeholder in source file
3:5: editor placeholder in source file
5:5: editor placeholder in source file

**Note: These errors should just be warnings and shouldn't affect the formatting of code (like Xcode does).**

**Comment by HassanTaleb90** [comment]
cc @ahoppen

**Comment by ahoppen** [comment]
Having an editor placeholder in a source file should generally be considered an error because the code won’t compile. swift-format could downgrade these errors to warnings as in https://github.com/apple/swift/pull/64382.
