### ISSUE TITLE
Issues in documentationCommentText.swift

### ISSUE THREAD

**Issue by HassanTaleb90** [apple/swift-format#564]
Commit: df5ad6548dddaed9ed1b6941d0d92b5031ccffc7

<img width="1334" alt="Screenshot 2023-07-12 at 9 35 28 AM" src="https://github.com/apple/swift-format/assets/49780321/4ad88246-c9d4-41c9-9939-8cff9f755187">

**Comment by allevato** [comment]
Can you provide some more details about your environment? What version of Xcode/Swift are you using?
