### ISSUE TITLE
Request: Force return in functions or variables

### ISSUE THREAD

**Issue by kimdv** [apple/swift-format#582]
This is an opinionated rule, so it should be opt-in. 

But a rule that enforces return.

Based in [this discussion](https://github.com/apple/swift-syntax/pull/2022#discussion_r1287171229) I think it could be a nice fit. 

Triggers

```swift
func foo() -> String {
"bar"
}
```

```swift
func foo: String {
"bar"
}
```

Non-triggers

```swift
func foo() -> String {
return "bar"
}
```

```swift
func foo() -> Void {
someApiCall()
}
```

```swift
func foo() {
someApiCall()
}
```

```swift
func foo: String {
return "bar"
}
```

**Comment by allevato** [comment]
@xedin and I recently chatted about some new rules and an `OmitReturns` rule was one of those. Combined with this request, it probably makes sense to have a single opt-in rule that has two modes: always omit single-expr returns and never omit single-expr returns.

**Comment by Matejkob** [comment]
Would the "never omit single-expr returns" mode add missing `return` statements?

**Comment by allevato** [comment]
Yes, I would expect it to not just diagnose the code, but insert or remove `return` where applicable when run in `format` mode.

Trying to think of any edge cases where either of those operations would break...

**Comment by Matejkob** [comment]
[This proposal](https://forums.swift.org/t/se-0380-if-and-switch-expressions/61899) could be quite a significant edge case.

**Comment by allevato** [comment]
Here's another one involving adding (or detecting the need for) `return`:

```swift
func f(closure: () -> Void) { closure() }
f { print("foo") }
// would become:
// f { return print("foo") }
```

That's still "correct" (semantically) but not likely to be desired. At the level of the `f` call, we can't tell that the closure isn't returning a value.

Result builders in general are another problem. There's no way to look at a closure or block syntactically and know that a result builder transform is being applied to it, so consider these two computed variables:

```swift
var body: some View {
  Text("blah")
}
var count: Int {
  5
}
```

Someone using a "mandatory `return`" rule might want the `return` inserted in `count` but not in `body`. There's no way we can distinguish those.

**Comment by xedin** [comment]
Omitting returns could be done syntactically but injecting them requires semantic analysis because of all the feature that rely on returns to be omitted.
