### ISSUE TITLE
`Optional<some Any>` is transformed to  `some Any?` which doesn't compile

### ISSUE THREAD

**Issue by dnadoba** [apple/swift-format#586]
```swift
func foo(bar: Optional<some Any>) {}
```
is transformed to
```swift
func foo(bar: some Any?) {}
```
but afterwards no longer compiles.

It either needs braces: 
```swift
func foo(bar: (some Any)?) {}
```
or kept as is.

Tested with latest `main` `8337523533bbd153cdac74c8fff4a1ac79a0b805`

**Comment by allevato** [comment]
Thanks for reporting this! It will be fixed by https://github.com/apple/swift-format/pull/589.

**Comment by dnadoba** [comment]
Awesome! That was really quick! Thanks a lot
