### ISSUE TITLE
`UseSynthesizedInitializer` warns even if `init` has non-standard attributes attached

### ISSUE THREAD

**Issue by dnadoba** [apple/swift-format#591]
```swift
struct Foo {
    var bar: Int

    @inlinable // warning: [UseSynthesizedInitializer] remove initializer and use the synthesized initializer
    init(bar: Int) {
        self.bar = bar
    }
}
```

`@inlinable` is required or otherwise it can't be used in other `@inlinable` code. Therefore this should not warn as it is not equivalent to the synthesised init.

**Comment by allevato** [comment]
Will be fixed by https://github.com/apple/swift-format/pull/592.

**Comment by dnadoba** [comment]
Very impressive report to fix time I must say! Thanks a lot again @allevato! Very appreciated
