### ISSUE TITLE
Assertion failed: Too many unresolved delimiter token lengths

### ISSUE THREAD

**Issue by glbrntt** [apple/swift-format#600]
swift-format [fails this assertion](https://github.com/apple/swift-format/blob/a2055fa49d0ea9b7056e2c664f7ae07adc6f80ff/Sources/SwiftFormat/PrettyPrint/PrettyPrint.swift#L681) when formatting or linting [this input](https://github.com/apple/swift-certificates/blob/0a442516157eaed34344db39279db847463d3644/Sources/X509/CertificatePrivateKey.swift) from file. It does not reproduce if read from stdin. 

I reproduced this on `main` ([a2055fa](https://github.com/apple/swift-format/commit/a2055fa49d0ea9b7056e2c664f7ae07adc6f80ff)) and 508.0.1.

**Comment by allevato** [comment]
Does this reproduce in the 509.0.0 release? I can't seem to reproduce it locally.

If it does repro, can you provide more info on how you're building and invoking swift-format?

**Comment by glbrntt** [comment]
It doesn't reproduce on 509.0.0 for me either.
