### ISSUE TITLE
Is there a configuration to exclude folders from formatting/linting?

### ISSUE THREAD

**Issue by sureshjoshi** [apple/swift-format#643]
This might be staring me in the face, but when I run `swift-format . -i --recursive` that includes all the `.build` folders that are created in my process (including checkouts and whatever else). 

So, what should be an instantaneous format turns into a minute or so.

I was hoping there was a config key or command line argument that would allow exclusions to certain folders.

**Comment by allevato** [comment]
I have a local branch that I need to finish up that would make `--recursive` ignore any dot-files/directories that it encounters during file system traversal. (You would still be able to format dot-files/directories if you passed them directly on the command line.)

I imagine that would cover the majority of users' needs without having to introduce explicit exclusions. Someone running swift-format should get the right behavior by default without having to think about the `.build` directory in their project's directory.

**Comment by sureshjoshi** [comment]
That would be awesome! That would cover the majority of use cases, for me anyways. 

Another case I can think of would be excluding unrelated files if that might provide a small perf boost. e.g. A large folder of generated web docs, or maybe a monorepo situation.

However that could possibly also be solved by giving each project of interest in the monorepo a swift-format instance on a core/thread - since SPM projects are generally well defined. 

And I suppose if you can change the generated docs folder, hiding that under a `.docs` could work too. 

In any case, just having dotfiles/dotfolders excluded is a huge perf boost for me.

**Comment by tscholze** [comment]
Hi team,
is there any update in excluding whole custom-defined directories like it is possible with the `swiftformat` (yes, confusing name collision)?
