### ISSUE TITLE
When using multi-line string literal, formatting results in invalid code in 509.0.0

### ISSUE THREAD

**Issue by treastrain** [apple/swift-format#652]
I'm using `swift-format 509.0.0`. If I prepare the following sample code and run `swift-format format`, it formats it into code that cannot be built.

This problem did not occur in `swift-format 508.0.0`. Is it a bug in `swift-format 509.0.0`?

```swift
import Foundation

@available(*, deprecated, renamed: "num", message: """
This is
multi-line
string
""")
func int() -> Int { 1 }
```

![](https://github.com/apple/swift-format/assets/13805382/6170bbb1-882e-4b7b-8d9e-26096153c5d6)

```sh
swift-format format -i Sources/main.swift
```

```swift
import Foundation

@available(
  *, deprecated, renamed: "num",
  message: """This is
  multi-line
  string"""
)
func int() -> Int { 1 }
```

![](https://github.com/apple/swift-format/assets/13805382/276ad02a-a7cb-4729-b72d-d55c39f02ace)

**Comment by allevato** [comment]
Have you observed this in other uses of multi-line strings or is it limited to attributes like `@available`?

**Comment by allevato** [comment]
Ah-ha, I see the problem. The string here is being represented by `SimpleStringLiteralExprSyntax`, which literally (😁) only appears in two places: `@available` annotations and `#sourceLocation` directives. And we don't handle that node when we format.

This was probably a recent-ish change in swift-syntax that, being so narrow, we didn't have specific test coverage for.
