### ISSUE TITLE
509 Regression: swift-format is deleting comments

### ISSUE THREAD

**Issue by stephencelis** [apple/swift-format#665]
I don't think swift-format should be proactively deleting code comments, but I'm seeing the following behavior with the latest release:

```sh
$ swift-format
withMacroTesting(
  // isRecording: true
) {
  super.invokeTest()
}
^D
```
```
withMacroTesting {
  super.invokeTest()
}
```

**Comment by allevato** [comment]
There are other cases where we check for the presence of comments to prevent otherwise destructive transformations; we should check that in `NoEmptyTrailingClosureParentheses` as well.
