### ISSUE TITLE
Can't run plugin with --configuration argument

### ISSUE THREAD

**Issue by JaapWijnen** [apple/swift-format#668]
I'm trying to run the following command locally by using the swift-format linting plugin.
`swift package lint-source-code --configuration .swift-format.json`
where `.swift-format.json` just contains the default config output by `swift-config dump-configuration` (created by the brew installed version of swift-format, not the plugin)
This results in the following error which seems to be a swift build related error instead of related to finding the configuration file. 
`error: The value '.swift-format.json' is invalid for '--configuration <configuration>'. Please provide one of 'debug' and 'release'.`

Interestingly enough this give me a different error when I pass the argument `--configuration debug` then it prints: 
`<unknown>: error: Unable to read configuration: The file “debug” couldn’t be opened because there is no such file.`

Am I using the plugin in the wrong way or is this a bug?

**Comment by sena-mike** [comment]
Also seeing this issue. Seems like it conflicts with the normal debug/release `configuration` parameter
