### ISSUE TITLE
Find config from CWD when formatting from stdin

### ISSUE THREAD

**Issue by judemille** [apple/swift-format#684]
It would appear that multiple tools prefer to feed swift-format via stdin.

Currently, swift-format seems to use the default configuration unless a file is specified on the CLI, when formatting a file from stdin. It would be preferable if the utility would find the configuration with the normal logic, but based on the CWD, when reading a file from stdin.

From a cursory look, this shouldn't be too hard to implement. I'll see if I can do it.

**Comment by allevato** [comment]
I think that's a sensible feature to have. Happy to review if you send a PR!

**Comment by judemille** [comment]
Finished via #685.
