### ISSUE TITLE
Running swift-format in a build phase does not seem to do anything.

### ISSUE THREAD

**Issue by BrentMifsud** [apple/swift-format#692]
Not sure what I am doing wrong here, swift-format works fine from the command line.

Here is my format phase:

```
export PATH="$PATH:/opt/homebrew/bin"

if which swift-format >/dev/null; then
    echo "Formatting with swift-format"
    swift-format format --in-place --recursive ${PROJECT_DIR}
else
    echo "warning: swift-format not installed"
fi
```

and my lint phase:

```
export PATH="$PATH:/opt/homebrew/bin"

if which swift-format >/dev/null; then
    echo "Linting with swift-format"
    swift-format lint --recursive --strict ${PROJECT_DIR}
else
    echo "warning: swift-format not installed"
fi
```

My configuration file is just the default from `swift-format dump-configuration` and is saved as .swift-format at the root of my project. 

and my build phase output for my format and lint step looks like this:

![image](https://github.com/apple/swift-format/assets/18543934/1289b423-4a25-4579-88f7-7aa001d72fb3)

It just seems to print out my echo statement, then nothing.

The weirdest thing is that if I run it manually from the terminal, it works fine.

Reproducible on an empty project as well.

**Comment by MahdiBM** [comment]
Is this a post-action or pre-action build script?
Using SwiftFormat, the pre-action wouldn't work either, probably due to a Xcode limitation.
Using post-action is not flawless for formatting, but it's still decent. Sometimes there is a file change after you trigger the build, which can result in a Xcode popup, but you can always just choose "Save anyway" or "Save the current thing" and it'll be fine.

**Comment by BrentMifsud** [comment]
Its neither a pre or post build script.

I am running it in a build phase, right after the built-in "run swift package plugin" build phase:

![image](https://github.com/apple/swift-format/assets/18543934/50b26717-ca43-4397-b815-e13ada528c15)

**Comment by MahdiBM** [comment]
What does this say? apart from the env vars it always injects.

<kbd> <img width="535" alt="Screenshot 2024-02-18 at 9 49 56 PM" src="https://github.com/apple/swift-format/assets/54685446/6d912172-93e2-4407-8963-dd41178f9dd2"> </kbd>

also, where is `PROJECT_DIR` coming from? Are you sure it exists?

**Comment by BrentMifsud** [comment]
I added an echo to show PROJECT_DIR its just a pointer to the project root directory. Xcode passes this env variable in for all builds.

Here is the expanded output:

![image](https://github.com/apple/swift-format/assets/18543934/747d0289-48f7-4b1f-8c57-c06df69c7bd6)

**Comment by MahdiBM** [comment]
hmm that seems about right.

**Comment by nyxdis** [comment]
This happens because the script is run in a sandbox by default. You can disable that in Build Settings ("User Script Sandboxing").
I guess an alternative would be to add your source files to the build phase input files, let the script write to the build phase output files (i.e. something like `swift-format format ${SCRIPT_INPUT_FILE_0} >${SCRIPT_OUTPUT_FILE_0}`), but I haven't figured out how to do that properly yet.

**Comment by BrentMifsud** [comment]
> This happens because the script is run in a sandbox by default. You can disable that in Build Settings ("User Script Sandboxing").
> 
> I guess an alternative would be to add your source files to the build phase input files, let the script write to the build phase output files (i.e. something like `swift-format format ${SCRIPT_INPUT_FILE_0} >${SCRIPT_OUTPUT_FILE_0}`), but I haven't figured out how to do that properly yet.

Ohhhhh thank you! I completely forgot about sandboxing. It's a new project so it's probably enabled by default or something. I'll try turning it off.

**Comment by BrentMifsud** [comment]
> This happens because the script is run in a sandbox by default. You can disable that in Build Settings ("User Script Sandboxing"). I guess an alternative would be to add your source files to the build phase input files, let the script write to the build phase output files (i.e. something like `swift-format format ${SCRIPT_INPUT_FILE_0} >${SCRIPT_OUTPUT_FILE_0}`), but I haven't figured out how to do that properly yet.

Thank you, this was the issue. I didn't realize I put script sandboxing on.

this tool really needs an Xcode build plugin.
