### ISSUE TITLE
Bundle swift-format in swift's official docker image

### ISSUE THREAD

**Issue by tknawara** [apple/swift-format#693]
Hi,

I'm wondering if it is possible to have swift-format pre-built in the [official swift docker image for linux](https://hub.docker.com/_/swift/), I'm currently using the docker image for my development with vs-code's dev containers, the image currently has all related swift tools (compiler, package manager, debugger, ...etc).

it will be very useful to have swift-format pre-built in the image as well.

Thanks in advance.

**Comment by kkk669** [comment]
The Swift 6.0 toolchain may bundle `swift-format` by default.

```console
$ docker container run -it --rm swiftlang/swift:nightly-main-jammy
 ################################################################
 #                                                              #
 # Swift Nightly Docker Image                                   #
 # Tag: swift-DEVELOPMENT-SNAPSHOT-2024-02-15-a                 #
 #                                                              #
 ################################################################

root@d8b207f893ec:/# which swift-format
/usr/bin/swift-format
```

**Comment by ahoppen** [comment]
Yes, main development snapshots contain swift-format since https://github.com/apple/swift/pull/71130
