### ISSUE TITLE
tag 510.0.0: "swift-format --version" prints "508.0.0"

### ISSUE THREAD

**Issue by mtgto** [apple/swift-format#698]
It seems version is fixed string "508.0.0" in https://github.com/apple/swift-format/blob/510.0.0/Sources/swift-format/VersionOptions.swift#L23

```console
❯ swift-format --version
508.0.0
```

**Comment by ahoppen** [comment]
Oh, good catch. I just tagged [510.0.1](https://github.com/apple/swift-format/releases/tag/510.0.1)
