### ISSUE TITLE
swift-format version 510.1.0, will it be flag as release?

### ISSUE THREAD

**Issue by emauricio** [apple/swift-format#707]
Hello there 👋,

I have a small question.

The version 510.1.0, will it be flagged as the latest release?

Since version 510.0 was missing some features from 509 (https://github.com/apple/swift-format/issues/697), but they have already been fixed (https://github.com/apple/swift-format/issues/697#issuecomment-2006954255).

I was wondering if there will be a new release soon, or if it's something that might need to wait.

Thank you in advance.

**Comment by ahoppen** [comment]
Here we go https://github.com/apple/swift-format/releases/tag/510.1.0
