### ISSUE TITLE
`swift-format --recursive` recurses into `.build`

### ISSUE THREAD

**Issue by GeorgeLyon** [apple/swift-format#739]
This issue makes it seem like `swift-format` should ignore hidden files: https://github.com/apple/swift-format/issues/643

This does not seem to be the behavior on macOS on the 510.1.0 release.

Steps to reproduce:
1. Create an empty directory `test`
2. Create an empty subdirectory `test/.build`
3. Run `echo "         struct Foo { }" > test/.build/Foo.swift`
4. Run `swift-format --recursive test`
5. `swift-format` will log that it formatted `Foo.swift` <-- This shouldn't happen

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://127902671

**Comment by bnbarham** [comment]
Unfortunately we branched quite early for 5.10 and didn't pick up the change you referenced. I've confirmed it is indeed fixed in 6.0, sorry about the confusion @GeorgeLyon!
