### ISSUE TITLE
[Question] Can I strict the order of Closure annotation?

### ISSUE THREAD

**Issue by psbss** [apple/swift-format#743]
Hello

Thank you so much development.

I would like to strict the order of closure annotation? like this.
Do you have any options or roadmap as a feature request?

```swift
🙅‍♂️ NG
let badClosure: @escaping @Sendable () -> Void

🙆‍♂️ Good
let goodClosure: @Sendable @escaping () -> Void
```

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://128436416
