### ISSUE TITLE
[Bugs?] `await` keyword mistake order when I use Swift-testing library.

### ISSUE THREAD

**Issue by psbss** [apple/swift-format#744]
Hello

Apple's new testing library [swift-testing]() may include from Xcode16.
So We started implementing of this library for our product but the format of `await` keyword order was mistake when I run swift-format command.

Examples

```swift
// mistake
#expect await (monitor.isAvailable == false)

// expected
#expect (await monitor.isAvailable == false)
```

Do we have a workaround?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://128436455

**Comment by ahoppen** [comment]
Am I correct in understanding that your original source code was

```swift
#expect (await monitor.isAvailable == false)
```

and that swift-format transformed it to 

```swift
#expect await (monitor.isAvailable == false)
```

I was unable to reproduce the issue by creating a file with the first contents (`await` inside the parentheses) and running `swift-format format /path/to/file.swift`. 

Which version of swift-format do you have installed?

**Comment by psbss** [comment]
Hi @ahoppen

Thanks for trying to reproduce.
That is correct.
We have `v0.53.8` installed

and this is our config

```.swiftformat
# disable
--disable wrapMultilineStatementBraces
--disable preferKeyPath
--disable preferForLoop

# format options
--stripunusedargs closure-only
--self init-only
--commas inline
--extensionacl on-declarations
--wrapparameters before-first
--wraparguments before-first
--maxwidth 120
--guardelse next-line

# version
--swiftversion 5.9

```

**Comment by ahoppen** [comment]
It looks like you are using https://github.com/nicklockwood/SwiftFormat, not this `swift-format`. Could you file an issue on that repository?

**Comment by psbss** [comment]
oh, I had a mistake. sorry
